/**
 * Every block of the robot language by its language `kind` (farmclaws part 3 spec §7): the
 * triggers, the statements except `do` (each action block is its own block), the action blocks
 * and the expressions, plus `helper` (Define helper). `var` is the variable getter and also gates
 * "Make a variable"; `if` covers both If and If … else. Unlocks list kinds in this order. Pure data.
 */

export const BLOCK_KINDS = [
  // triggers
  'morning',
  'atTime',
  'bagFull',
  'startsRaining',
  'every',
  // control
  'repeatTimes',
  'repeatUntil',
  'repeatForever',
  'if',
  'forEachTile',
  'set',
  'change',
  'var',
  'helper',
  'runHelper',
  // actions
  'move',
  'turn',
  'goTo',
  'water',
  'refill',
  'harvest',
  'deposit',
  'take',
  'till',
  'plant',
  'powerDown',
  'wait',
  'say',
  // sensors
  'cropIsReady',
  'soilIsDry',
  'tileIsTilled',
  'cropIs',
  'bagIsFull',
  'bagHas',
  'atEdgeOf',
  'tokensBelow',
  'tileAheadIs',
  'itIsRaining',
  'timeIsAfter',
  // values
  'num',
  'text',
  'yes',
  'item',
  'tile',
  'myTile',
  'tileAhead',
  'tokensLeft',
  'countInBag',
  'arith',
  'compare',
  'and',
  'or',
  'not',
] as const;
export type BlockKind = (typeof BLOCK_KINDS)[number];

export type BlockCategory = 'triggers' | 'control' | 'actions' | 'sensors' | 'values';

/**
 * Each kind's category; BLOCK_KINDS lists the categories in this order. `var` sits in Control with
 * `set` and `change` (it gates "Make a variable"); the toolbox shows the `var` getter under Values.
 */
export const BLOCK_CATEGORY: Readonly<Record<BlockKind, BlockCategory>> = {
  morning: 'triggers',
  atTime: 'triggers',
  bagFull: 'triggers',
  startsRaining: 'triggers',
  every: 'triggers',
  repeatTimes: 'control',
  repeatUntil: 'control',
  repeatForever: 'control',
  if: 'control',
  forEachTile: 'control',
  set: 'control',
  change: 'control',
  var: 'control',
  helper: 'control',
  runHelper: 'control',
  move: 'actions',
  turn: 'actions',
  goTo: 'actions',
  water: 'actions',
  refill: 'actions',
  harvest: 'actions',
  deposit: 'actions',
  take: 'actions',
  till: 'actions',
  plant: 'actions',
  powerDown: 'actions',
  wait: 'actions',
  say: 'actions',
  cropIsReady: 'sensors',
  soilIsDry: 'sensors',
  tileIsTilled: 'sensors',
  cropIs: 'sensors',
  bagIsFull: 'sensors',
  bagHas: 'sensors',
  atEdgeOf: 'sensors',
  tokensBelow: 'sensors',
  tileAheadIs: 'sensors',
  itIsRaining: 'sensors',
  timeIsAfter: 'sensors',
  num: 'values',
  text: 'values',
  yes: 'values',
  item: 'values',
  tile: 'values',
  myTile: 'values',
  tileAhead: 'values',
  tokensLeft: 'values',
  countInBag: 'values',
  arith: 'values',
  compare: 'values',
  and: 'values',
  or: 'values',
  not: 'values',
};
